### ISSUE TITLE
document "inheritance" parameter for koji_tag

### ISSUE THREAD

**Issue by ktdreyer** [ktdreyer/koji-ansible#186]
The inline docs for `koji_tag` have this (un)helpful description for the `inheritance` parameter:

```yaml
inheritance:
  description:
    - How to set inheritance. what happens when it's unset.
```

Let's write a real description here. We should document "maxdepth", "intransitive", "parent", "noconfig", "pkg_filter", and "priority", copying from https://github.com/ktdreyer/koji-ansible/blob/master/library/koji_tag_inheritance.py
