### ISSUE TITLE
support blocking packages

### ISSUE THREAD

**Issue by ktdreyer** [ktdreyer/koji-ansible#2]
Here is how to define a package set for a tag today:

```yaml
  - name: Create a main product koji tag
    koji_tag:
      name: ceph-3.2-foo
      state: present
      packages:
        kdreyer:
          - ansible
          - ceph
          - ceph-ansible
```

This means I can only "whitelist" (`koji add-pkg`) builds. I need to be able to "blacklist" them (`koji block-pkg`).

Need to play around with whether it makes sense to build this into the `packages` parameter. Something like:
```yaml
      packages:
        kdreyer:
          - ansible
          - ceph:
              blocked: true
          - ceph-ansible
```

(This would also make room for the `extra_arches` feature of `packageListAdd`.)
