### ISSUE TITLE
new koji_tag_inheritance module

### ISSUE THREAD

**Issue by ktdreyer** [ktdreyer/koji-ansible#26]
Currently the `koji_tag` module is all-or-nothing when it comes to tag inheritance management. Either you can manage a tag's inheritance completely with Ansible, or else you cannot manage it at all with Ansible.

[MBS](https://fedoraproject.org/wiki/Changes/ModuleBuildService) will dynamically manage some of a tag's inheritance, so this conflicts with what koji-ansible tries to do.

To provide finer-grained tag inheritance management and avoid clobbering MBS, we can introduce a new `koji_tag_inheritance` Ansible module. This will work like:

```yaml
koji_tag_inheritance:
  parent: my-parent-tag
  child: my-child-tag
  priority: 10
```

It will be preferable to set inheritance using the `koji_tag` module directly, but this advanced module will assist users writing playbooks that must work with MBS.
