### ISSUE TITLE
support tagging builds

### ISSUE THREAD

**Issue by ktdreyer** [ktdreyer/koji-ansible#3]
We need an idempotent way to tag builds during a playbook run. Something like:

```yaml
  - name: Tag a build into the ceph-3.1-rhel-7-override tag
    koji_tag_build:
      koji: kojidev
      name: redhat-release-server-1.0.el7
      tag: ceph-3.1-rhel-7-override
      state: present
```
