### ISSUE TITLE
koji_tag_inheritance cannot replace a parent with the same priority

### ISSUE THREAD

**Issue by ktdreyer** [ktdreyer/koji-ansible#34]
I have three tags, `my-child-tag`, and `parent-tag-a`, and `parent-tag-b`. The child tag currently inherits from `parent-tag-a`:
```
$ kojidev taginfo my-child-tag
Tag: my-child-tag [22]
Arches: None
Groups: 
Tag options:
Inheritance:
  0    .... parent-tag-a [23]
```
If I try to switch that to `parent-tag-b`, the hub denies the operation:

```yaml
  - name: Set partial inheritance
    koji_tag_inheritance:
      child_tag: my-child-tag
      parent_tag: parent-tag-b
      priority: 0
      state: present
```

The error from the hub is:
```
    __koji__kojidev.GenericError: Inheritance priorities must be unique (pri 0: [24, 23] )
```

To fix this bug, we need to delete (`delete link`) any existing relationship at the given priority when we set our new relationship.
