### ISSUE TITLE
add support for regenerating repositories

### ISSUE THREAD

**Issue by ktdreyer** [ktdreyer/koji-ansible#47]
When setting up an entirely new build tag and target, it's a good idea to generate the repositories for the first time with the `koji regen-repo` command.

I'm thinking of a new `koji_repo` module, like:

```yaml
  handlers:
    - name: regenerate ktdreyer-el7-build
      koji_repo:
        name: ktdreyer-el7-build
        state: regenerated
```

We could make this module return the values from `getRepo(name)` and the task_id as well.
