### ISSUE TITLE
error when swapping priority of two external repos

### ISSUE THREAD

**Issue by ktdreyer** [ktdreyer/koji-ansible#52]
I have a tag that uses several external repositories, like so:

```yaml
  - name: Add ktdreyer-el7-build tag
    koji_tag:
      name: ktdreyer-el7-build
      arches: x86_64
      external_repos:
      - repo: el7
        priority: 0
      - repo: el7-updates
        priority: 5
      - repo: el7-extras
        priority: 10
      - repo: epel7
        priority: 15
```

I ran into an interesting problem here. CentOS Extras ("`el7-extras`") happens to include ancient versions of some packages that are newer in EPEL 7  (eg. ansible 2.4 is in `el7-extras`, ansible 2.8 is in EPEL 7). I guess the CentOS administrators do not remove packages from CentOS 7 Extras that are gone in RHEL and subsequently added to EPEL 7.

Since Koji uses "priority" instead of NVR comparisons when it chooses which builds to index, I get the ancient version of ansible in my buildroot.

To fix this, I need to change the priorities to make `epel7` higher than `el7-extras`. I swapped the priorities like so:

```yaml
      - repo: epel7
        priority: 10
      - repo: el7-extras
        priority: 15
```

This raises an error:

```
    __koji__kojidev.GenericError: tag ktdreyer-el7-build already associated with an external repo at priority 10
```

It seems that we cannot handle this type of priority re-ordering correctly.

**Comment by ktdreyer** [comment]
This is a good thing to test with the integration suite against a real hub.

**Comment by ktdreyer** [comment]
We have an integration test suite running in Travis CI now, and I can reproduce this bug with that. Here's a minimal test case:

```yaml
- name: Create an external repo for CentOS
  koji_external_repo:
    name: external-repos-1-os
    url: http://mirror.centos.org/centos/7/os/$arch/
    state: present

- name: Create an external repo for EPEL
  koji_external_repo:
    name: external-repos-1-epel
    url: http://download.fedoraproject.org/pub/epel/7/$arch
    state: present

- name: Set up the two external repos
  koji_tag:
    name: external-repos-1
    state: present
    external_repos:
    - repo: external-repos-1-os
      priority: 10
    - repo: external-repos-1-epel
      priority: 20

- name: Swap the external repo priorities for the OS and EPEL
  koji_tag:
    name: external-repos-1
    external_repos:
    - repo: external-repos-1-epel
      priority: 10
    - repo: external-repos-1-os
      priority: 20
```

The final `koji_tag` task fails with this error:

```
GenericError: tag external-repos-1 already associated with an external repo at priority 10
```
