### ISSUE TITLE
koji_tag_inheritance "state: absent" should not require "priority"

### ISSUE THREAD

**Issue by ktdreyer** [ktdreyer/koji-ansible#57]
When I use `state: absent` in order to delete an inheritance relationship, I get an error:

```yaml
- koji_tag_inheritance:
    parent_tag: my-parent-tag
    child_tag: my-child-tag
    state: absent
```

```
msg: 'missing required arguments: priority'
```

We should be able to delete this inheritance relationship without having to specify the priority integer.
